### ISSUE TITLE
Adding support for OneWire

### ISSUE THREAD

**Issue by djbwise** [austinbv/dino#18]
Where and how do you guys envision one adding support for things like this: https://www.sparkfun.com/products/11050?

Would this be useful as part of the library/framework? Otherwise it obviously can just be a component in my existing project.

Also, what are the thoughts of adding more libraries like this to the arduino bootstrap, that can be called from ruby. This would allow us to take advantage of already written arduino libraries.

**Comment by MinasMazar** [comment]
I noticed OneWire libs are not included in DinoCLI::Generator::LIB_FILENAMES. Is there a particular reason for this?

**Comment by vickash** [comment]
You're right. They aren't included in there because the files themselves aren't included in the repository yet. I had installed the OneWire library so long ago, that when I started adding DS18B20 support, I forgot it wasn't part of the IDE.

I'll add the library itself and the missing references into the wip branch.

The library you need is, in fact, the one from here: http://www.pjrc.com/teensy/td_libs_OneWire.html. In the meantime, you should be able to unzip, drop the .h and .cpp files into the sketch folder and it will work.
