### ISSUE TITLE
Read digital output state

### ISSUE THREAD

**Issue by justinledwards** [austinbv/dino#56]
Is this possible with dino?   I have had my arduino less than 24 hours and went through the 12 chapter book it came with last night, and am trying to integrate it into a rails app today.  

I am testing with just one LED across the room right now.   I am looking to check the state of the LED (or later on relay).   I know that I can set a variable on the state change and read that variable, but if possible I'd like to actually see the state from the hardware.   When I try to add_digital_hardware the LED no longer functions, and when I try digital_read, it returns nil no matter what the state.  Any help would be appreciated.   

Wanting to do something like this.  
http://forum.arduino.cc/index.php/topic,41954.0.html

**Comment by vickash** [comment]
This is now possible if you make your own class by mashing together the `Basic::DigitalInput` and `Basic::DigitalOutput` classes. Just make sure to leave out the `Setup::Input` module, since that would set the pin mode to INPUT and then writing would just affect the pullup resistor, which you don't want. Everything else should just work together.

I don't think this should be a standard feature though, since each component already caches it's state in a `@state` variable. Since one of our basic assumptions is that we have complete control over the board, that value should be trusted and used instead.
